exec-once = systemctl --user start hyprpolkitagent

exec-once = swaync
exec-once = blueman-applet
exec-once = waybar
#exec-once = hyprlauncher -d
exec-once = hypridle
exec-once = hyprsunset
exec-once = udiskie
exec-once = wl-paste --watch clipvault store --min-entry-length 2 --max-entries 800 --max-entry-age 30d
exec-once = awww-daemon

env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

exec = sleep 1
exec = awww img -o DP-2 "/home/kot/Images/assets/bg/n/1600272470.finalcord_zoru-lofi.gif"
exec = awww img -o DP-3 "/home/kot/Images/assets/bg/4562118-pinkpoffinz-puffi_(pinkpoffinz)-canid-canine-domestic_cat-felid-feline-felis-fox-hybrid-mammal.jpg"
exec = awww img -o eDP-1 "/home/kot/Images/assets/bg/413289066_1030075811408400_8354114380093909779_n.jpg"

exec-once = arrpc
exec-once = signal-desktop
exec-once = steam
exec-once = vesktop
