exec-once = systemctl --user start hyprpolkitagent
exec-once = /usr/lib/pam_kwallet_init

exec-once = swaync
exec-once = blueman-applet
exec-once = waybar
#exec-once = hyprlauncher -d
exec-once = hypridle
exec-once = hyprsunset
exec-once = udiskie
exec-once = wl-paste --watch clipvault store --min-entry-length 2 --max-entries 800 --max-entry-age 30d
exec-once = swww-daemon

$gnome-schema = org.gnome.desktop.interface

$gtk_theme = $(grep 'gtk-theme-name' "$config" | sed 's/.*\s*=\s*//')
$icon_theme = $(grep 'gtk-icon-theme-name' "$config" | sed 's/.*\s*=\s*//')
$cursor_theme = $(grep 'gtk-cursor-theme-name' "$config" | sed 's/.*\s*=\s*//')
$font_name = $(grep 'gtk-font-name' "$config" | sed 's/.*\s*=\s*//')
#exec = gsettings set $gnome-schema gtk-theme 'Your theme'
#exec = gsettings set $gnome-schema icon-theme 'Your icon theme'
#exec = gsettings set $gnome-schema cursor-theme 'Your cursor Theme'
#exec = gsettings set $gnome-schema font-name 'Adwaita Mono'

exec = swww img -o DP-1 "/home/kot/Images/assets/bg/n/1600272470.finalcord_zoru-lofi.gif"
exec = swww img -o DP-2 "/home/kot/Images/assets/bg/4562118-pinkpoffinz-puffi_(pinkpoffinz)-canid-canine-domestic_cat-felid-feline-felis-fox-hybrid-mammal.jpg"
exec = swww img -o eDP-1 "/home/kot/Images/assets/bg/413289066_1030075811408400_8354114380093909779_n.jpg"

env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = SECRET_SERVICE_BACKEND,kwallet
env = KDE_SESSION_VERSION,6
env = QT_KEYCHAIN_BACKEND,kwallet

#exec = wait 2
exec-once = arrpc
exec-once = signal-desktop --password-store="kwallet6"
exec-once = vesktop
exec-once = steam
