monitor = desc:GIGA-BYTE TECHNOLOGY CO. LTD. G27Q, 2560x1440@143.97, 0x0, 1, bitdepth, 10, vrr, 2
monitor = desc:Samsung Electric Company SyncMaster, 1680x1050@59.88, -1050x0, 1, transform, 1

xwayland {
    enabled = true
    use_nearest_neighbor = true
    # force_zero_scaling = false
    # create_abstract_socket = false
}

render {
    direct_scanout = 2
    cm_enabled = true
    cm_fs_passthrough = 2
    cm_auto_hdr = 1
    new_render_scheduling = false
}

windowrule = match:float true, opacity 0.75
windowrule = match:float true, immediate yes
windowrule = match:class xdg-desktop*, float on
windowrule = match:class xdg-desktop*, center on
windowrule = match:class xdg-desktop*, opacity 0.5
