input {
    kb_layout = us
    numlock_by_default = false
    repeat_rate = 25
    repeat_delay = 500

    sensitivity = -0.7
    accel_profile = flat
    follow_mouse = 1

    touchpad {
        disable_while_typing = false
    }
}

binds {
    disable_keybind_grabbing = false
    drag_threshold = 20
}

cursor {
    min_refresh_rate = 10
    hotspot_padding = 1
    no_warps = false
    hide_on_key_press = false
    warp_back_after_non_mouse_input = false
}

# remember to setup keybinds like hyprpicker here
# rofi -show combi -modes combi -combi-modes "window,drun,run"
bind = SUPER, V, exec, clipvault list | rofi -dmenu -display-columns 2 | clipvault get | wl-copy
bind = SUPER_ALT, F4, exec, hyprshutdown -t 'Shutting down...' --post-cmd 'systemctl suspend'
# bind = SUPER, F10, pass, class:^(com\.obsproject\.Studio)$
# bind = SUPER_SHIFT, A, global, coolApp:myToggle

bind = SUPER_SHIFT, up, movewindow, u
bind = SUPER_SHIFT, down, movewindow, d
bind = SUPER_SHIFT, left, movewindow, l
bind = SUPER_SHIFT, right, movewindow, r

########## From wiki ##########
# Switch to a submap called `resize`.
bind = ALT, R, submap, resize

# Start a submap called "resize".
submap = resize

# Set repeatable binds for resizing the active window.
binde = , right, resizeactive, 10 0
binde = , left, resizeactive, -10 0
binde = , up, resizeactive, 0 -10
binde = , down, resizeactive, 0 10

# Use `reset` to go back to the global submap
bind = , escape, submap, reset

# Reset the submap, which will return to the global submap
submap = reset

bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
# Requires playerctl
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioNext, exec, playerctl next
###################
$terminal = kitty
$filemanager = thunar
$menu = rofi -show combi -modes combi -combi-modes "window,drun,run"
$screenshotpath = "$(xdg-user-dir PICTURES)/Copies d'écran/$(date +'%Y-%m-%d-%H%M%S-%3N_grim.png')"
bind = SUPER, SPACE, exec, $menu                                                       
bind = SUPER, R, exec, $menu
bind = SUPER, RETURN, exec, $terminal
bind = SUPER, E, exec, $filemanager
bind = ALT, Q, killactive,
bind = SUPER_SHIFT, RETURN, togglefloating,
bind = SUPER, F, fullscreen, toggle
bind = SUPER, D, exec, swaync-client -t
bind = SUPER_ALT, f, exec, floorp
bind = , Print, exec, hyprshot -z -m region -o "~/Images/Copies d'écran/"
bind = SHIFT, Print, exec, hyprshot -z -m active -m window -o "~/Images/Copies d'écran/"
bind = CTRL, Print, exec, hyprshot -z -m active -o output "~/Images/Copies d'écran/"
