globinclude kitty.d/**/*.conf

font_family family="JetBrains Mono"
font_size 10

scrollbar hovered
background_opacity 0.5
visual_bell_diration 0.2
scrollback_lines -1
remember_window_size no
initial_window_width  100c
initial_window_height 30c
